/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface OrderCreateInput {
  data: {
    items: OrderItem[];
  };
}

export interface OrderItem {
  productId: string;
  quantity: number;
}

export interface OrderSearchInput {
  filterBy?: {
    createdAt?: {
      from?: Date;
      to?: Date;
    };
    status?: 'created' | 'in-progress' | 'on-the-way' | 'delivered';
  };
  searchBy?: {
    appUserId?: string;
    id?: string;
    restaurantId?: string;
  };
}

export interface OrderUpdateInput {
  data: {
    itemsToAdd?: OrderItem[];
    itemsToUpdate?: OrderItem[];
    productsToRemove?: string[];
  };
  searchBy: {
    id: string;
  };
}

export interface OrderUpdateStatusInput {
  data: {
    status: 'in-progress' | 'on-the-way' | 'delivered';
  };
  searchBy: {
    id: string;
  };
}
