/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface AppUserCreateInput {
  data: {
    address: string;
    firstName: string;
    lastName: string;
    phone: string;
    type: 'ADMIN' | 'CUSTOMER';
    userId: string;
  };
}

export interface AppUserSearchInput {
  searchBy?: {
    id?: string;
    userId?: string;
  };
}

export interface AppUserUpdateInput {
  data: {
    address?: string;
    firstName?: string;
    lastName?: string;
    phone?: string;
    type?: 'ADMIN' | 'CUSTOMER';
  };
  searchBy: {
    id: string;
  };
}
