@baseUrl = http://localhost:8080/api/v1/business/orders
@contentType = application/json

### invalid input
POST {{baseUrl}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer 65245e6d71bf8e5c8c39a067

{
  "ad": "juan"
}


### Create valid order, admin user
POST {{baseUrl}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer 65245e6d71bf8e5c8c39a067

{
  "items": [
    {
        "productId": "65257a3cbcc64b22c8c480ac",
        "quantity": 2
    },
    {
        "productId": "65257ae0bcc64b22c8c480ad",
        "quantity": 1
    }
  ]
}

### Create valid oder, client user
POST {{baseUrl}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer 65245eeb71bf8e5c8c39a068

{
  "items": [
    {
        "productId": "65257bd4bcc64b22c8c480af",
        "quantity": 1
    }
  ]
}

### List
GET {{baseUrl}} HTTP/1.1

### List
GET {{baseUrl}}?status=in-progress HTTP/1.1

### List
GET {{baseUrl}}?status=created HTTP/1.1

### List
GET {{baseUrl}}?createdAtFrom=2023-12-01&createdAtTo=2024-02-01 HTTP/1.1

### List
GET {{baseUrl}}?status=delivered HTTP/1.1

### List
GET {{baseUrl}}?restaurantId=6524bdcaa6a1f5ce55ae8abf HTTP/1.1

### List
GET {{baseUrl}}?restaurantId=6524c1fca4b55b0f071a23e0 HTTP/1.1

### List
GET {{baseUrl}}?restaurantId=6524bdcaa6a1f5ce55ae8abf&&appUserId=65245e6d71bf8e5c8c39a067 HTTP/1.1



### Update order, invalid input
PATCH {{baseUrl}}/6525f9d6aeb0aa9fecc9dfda HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer 65245eeb71bf8e5c8c39a068

{
  "itemsToUpdate": [
    {
        "productId": "65257bd4bcc64b22c8c480af",
        "quantity": -19
    }
  ]
}

### Update order, update quantity
PATCH {{baseUrl}}/6525f9d6aeb0aa9fecc9dfda HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer 65245eeb71bf8e5c8c39a068

{
  "itemsToUpdate": [
    {
        "productId": "65257bd4bcc64b22c8c480af",
        "quantity": 1
    }
  ]
}

### Update order, remove product
PATCH {{baseUrl}}/6525f9d6aeb0aa9fecc9dfda HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer 65245eeb71bf8e5c8c39a068

{
  "productsToRemove": [
    "65257bf2bcc64b22c8c480b0"
  ]
}

### forbidden product update
PATCH {{baseUrl}}/6525f9d6aeb0aa9fecc9dfda HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer 65245e6d71bf8e5c8c39a067

{
  "productsToRemove": [
    "65257bf2bcc64b22c8c480b0"
  ]
}


### update status
PATCH {{baseUrl}}/6525ffa0b5ceb1dc4457dd64/status HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer 65245e6d71bf8e5c8c39a067

{
  "status": "in-progress"
}


### Delete order
DELETE {{baseUrl}}/6525fdd52b5958543030a698 HTTP/1.1
Authorization: Bearer 65245e6d71bf8e5c8c39a067

### Delete order
DELETE {{baseUrl}}/6525fdd52b5958543030a698 HTTP/1.1
Authorization: Bearer 65245e6d71bf8e5c8c39a067




### invalid mongo id
GET {{baseUrl}}/100200312 HTTP/1.1

### not found id
GET {{baseUrl}}/65aa83e349635689f1bb8cb2 HTTP/1.1

### normal
GET {{baseUrl}}/6525ffa0b5ceb1dc4457dd64 HTTP/1.1


